# --------------------------------------------- HYDRA -----------------------------------------------------
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: custom

hydra:
  output_subdir: null
  run:  
    dir: .

# ----------------------------------------------- PIPELINE -------------------------------------------------

pipeline:
  classify_vehicles: True  


# ------------------------------------------------- NODES --------------------------------------------------

video_reader:
  src: test_videos/test_video.mp4 # путь до файла обработки или номер камеры (int) или ссылки на m3u8 / rtsp поток
  skip_frames: 2   # пропускать каждый n-ый кадр (0 - не пропускать)


detection_node:
  weight_pth: weights/yolo26s.pt  # Путь до модели .pt или .engine (TensorRT)
  classes_to_detect: [2,3,5,7]  # весь транспорт из классов COCO
  confidence: 0.10  # Порог уверенности детектора (чем больше значение, тем меньше находит)


vehicle_classifier_node:
  model_path: weights/resnet34_vehicle_classifier_224.pth  
  class_names: None 
  input_size: 224
  device: cuda:0
  half: True

  classifier_batch_size: 8
  classify_every_n_frames: 2  
  crop_padding: 10
  min_conf: 0.0


show_node:
  scale : 0.6  # Масштабирование итогового окна результатов при imshow=True
  imshow: True  # Нужно ли выводить видео в процессе обработки
  fps_counter_N_frames_stat : 24  # Окно усредения fsp счетчика
  draw_fps_info : True  # Указывать ли fps обработки
  show_roi: True  # Показывать ли регионы примыкающих дорог 
  show_only_yolo_detections : True  # Отображать лишь результаты детекции без учета трекинга и прочей логики кода
  roads_info: configs/entry_exit_lanes.json  # json файл с координатами дорог на видео
  
  colors_of_roads: # in bgr
    1: [102,204,255] #ffcc66
    2: [0,0,170] #aa0000
    3: [17,70,10] #0a3e11
    4: [120,56,126] #7e3878
    5: [30,105,215] #d2691e